### ISSUE TITLE
Replace methods in helper.js with open source alternatives

### ISSUE THREAD

**Issue by alexgibson** [h5bp/mobile-boilerplate#164]
There has been some discussion in issue #159 that it might be a good idea to replace some of the methods in `helper.js` with open source alternatives, pulling in JS plugins from other repos that are actively maintained etc. The aim is to move away from a monolithic file of code snippets, into something more modular and that is easier to maintain.

Opening this thread for ideas, suggestions and discussion... :)

Some alternative repos / plugins for some of the more commonly used MBP methods:

hide url bar - 
https://github.com/scottjehl/Hide-Address-Bar

orientation fix - 
https://github.com/scottjehl/iOS-Orientationchange-Fix

tap plugins - 
https://github.com/borismus/pointer.js
https://github.com/alexgibson/tap.js
https://github.com/cheeaun/tappable

**Comment by arthurvr** [comment]
Hey there. Thanks for reporting this. We appreciate it :) I'm going to close this as this project is [deprecated](https://github.com/h5bp/mobile-boilerplate/commit/78c876e065d90fa87eb55b04b7c127769d66dc54).
