### ISSUE TITLE
Add support for pointer events

### ISSUE THREAD

**Issue by alexgibson** [h5bp/mobile-boilerplate#178]
Given that the current implementation of fastButton in MBP does not support pointer events for IE10, should we consider moving to a new library that can consolidate mouse/touch and pointer?

Two possibles are:

* [hand.js](http://blogs.msdn.com/b/eternalcoding/archive/2013/01/16/hand-js-a-polyfill-for-supporting-pointer-events-on-every-browser.aspx)
* [pointer.js](https://github.com/borismus/pointer.js/)

Alternatively, could we support IE10 simply by using `-ms-touch-action: none;`

https://hacks.mozilla.org/2013/04/detecting-touch-its-the-why-not-the-how/

Just throwing this out for discussion...

**Comment by arthurvr** [comment]
Hey there. Thanks for reporting this. We appreciate it :) I'm going to close this as this project is [deprecated](https://github.com/h5bp/mobile-boilerplate/commit/78c876e065d90fa87eb55b04b7c127769d66dc54).
