### ISSUE TITLE
Screen size VS. Resolution

### ISSUE THREAD

**Issue by Billy-** [h5bp/mobile-boilerplate#213]
This issue is regarding the [Mobile Matrices Wiki page](https://github.com/h5bp/mobile-boilerplate/wiki/Mobile-Matrices).

> It is primarily for a quick reference sheet when trying to target a specific platform with CSS media queries.

I wish I could say the above quote was true however when working with media queries the screen resolution is totally irrelevant. For example the resolution of the iPhone 4/4s is 640 × 960 px, but the screen size is 320 x 480 px. Many of the items in this list have resolutions that are very different to the size of the screen that you must use in your media queries for them to work.

**Comment by arthurvr** [comment]
Hey there. Thanks for reporting this. We appreciate it :) I'm going to close this as this project is [deprecated](https://github.com/h5bp/mobile-boilerplate/commit/78c876e065d90fa87eb55b04b7c127769d66dc54).
