### ISSUE TITLE
Docs: Google Analytics for Mobile Websites has been deprecated

### ISSUE THREAD

**Issue by slavanga** [h5bp/mobile-boilerplate#230]
Google Analytics for Mobile Websites has been [deprecated] (https://developers.google.com/analytics/devguides/collection/other/mobileWebsites) as of April 2, 2014. The [docs] (https://github.com/h5bp/mobile-boilerplate/blob/master/doc/extend.md#google-analytics-for-mobile) should be updated. I'm not sure how the new Measurement Protocol is different from the old method.

**Comment by arthurvr** [comment]
Hey there. Thanks for reporting this. We appreciate it :) I'm going to close this as this project is [deprecated](https://github.com/h5bp/mobile-boilerplate/commit/78c876e065d90fa87eb55b04b7c127769d66dc54).
