### ISSUE TITLE
Add `Screen Orientation API` to `docs/extend.md`

### ISSUE THREAD

**Issue by arthurvr** [h5bp/mobile-boilerplate#236]
Already implemented in [Chrome 38+](https://twitter.com/mrdoob/status/540147861326139392). Spec: https://w3c.github.io/screen-orientation/

**Comment by tx5** [comment]
@arthurvr WHY U KEEP CLOSING ISSUES ??

**Comment by tx5** [comment]
@arthurvr WHY U KEEP CLOSING ISSUES ??

**Comment by arthurvr** [comment]
Hey there. Thanks for reporting this. We appreciate it :) I'm going to close this as this project is [deprecated](https://github.com/h5bp/mobile-boilerplate/commit/78c876e065d90fa87eb55b04b7c127769d66dc54).
