### ISSUE TITLE
Splash images

### ISSUE THREAD

**Issue by scruffian** [h5bp/mobile-boilerplate#237]
The only information in the mobile boiler plate about splash images is this:

`<link rel="apple-touch-startup-image" href="img/l/splash.png">`

I think the situation is significantly more complex than this. Here is a snippet which attempts to deal with the situation on the iPhone 6 and 6+, but there are obviously a lot more variants:

http://stackoverflow.com/questions/26026492/correct-size-for-apple-touch-startup-image-in-iphone-6-iphone-6-plus/26057714#26057714

Is this something you would consider adding to the mobile boiler plate?

**Comment by arthurvr** [comment]
Hey there. Thanks for reporting this. We appreciate it :) I'm going to close this as this project is [deprecated](https://github.com/h5bp/mobile-boilerplate/commit/78c876e065d90fa87eb55b04b7c127769d66dc54).
