### ISSUE TITLE
Wiki Suggested Device List is super out of date

### ISSUE THREAD

**Issue by justinschier** [h5bp/mobile-boilerplate#238]
https://github.com/h5bp/mobile-boilerplate/wiki/Suggested-Device-List

From like 4 years ago, not relevant any longer, probably.

**Comment by filipelinhares** [comment]
+1

**Comment by arthurvr** [comment]
Hey there. Thanks for reporting this. We appreciate it :) I'm going to close this as this project is [deprecated](https://github.com/h5bp/mobile-boilerplate/commit/78c876e065d90fa87eb55b04b7c127769d66dc54).
