### ISSUE TITLE
Has anyone tested the MBP.fastButton helper with ReactJs

### ISSUE THREAD

**Issue by kevbook** [h5bp/mobile-boilerplate#243]
React seem to use "synthetic events", I don't know how to test it, just its just a question to the community.

**Comment by arthurvr** [comment]
Hey there. Thanks for reporting this. We appreciate it :) I'm going to close this as this project is [deprecated](https://github.com/h5bp/mobile-boilerplate/commit/78c876e065d90fa87eb55b04b7c127769d66dc54).
