### ISSUE TITLE
Why not recommend to use Mobile Boilerplate?

### ISSUE THREAD

**Issue by Loyalsoldier** [h5bp/mobile-boilerplate#246]
I compare Mobile Boilerplate to HTML5 Boilerplate. There is more head information about creating a webapp for android and iOS platform in Mobile Boilerplate, which is great for creating a mobile-first, HTML5 website.
As far as I am concerned, **Mobile Boilerplate** is better. Why you guys recommend to use HTML5 Boilerplate?

**Comment by frontenddeveloping** [comment]
+1, mobile is everywhere
